name: Test Custom Runner

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: self-hosted  # Use the custom runner you set up

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Assuming you have tests set up in your repo


